theme: jekyll-theme-slate
title: Welcome to the BARS Management UI
name: PSFramework
description: The project to ease management of MW BAckup, automate database Restores and SQL Server Security for DBAs
